---

- name: role-test-vault | config | template config
  template:
    src: templates/config.j2
    dest: /tmp/config

- name: role-test-vault | config | debug var 
  debug: var='vault_encrypted_var'
